### ISSUE TITLE
Pass breakpoint context to mixin

### ISSUE THREAD

**Issue by qtgye** [qtgye/simple-grids#4]
Allow breakpoint context override when using `span` mixin:
```scss
@include grid-breakpoint(md) {
   width: span(2 of 4 at xl); // Will use settings from xl breakpoint instead of md.
}
```
